# Generated by Django 2.1.3 on 2018-11-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='_progress',
            field=models.CharField(db_column='progress', max_length=30),
        ),
    ]
