# Generated by Django 2.1.3 on 2018-11-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20181115_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='_progress',
            new_name='progress',
        ),
    ]
