# Generated by Django 2.1.3 on 2018-11-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_week_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='complete',
        ),
    ]
