# Generated by Django 2.1.3 on 2018-11-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_remove_week_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
