# Generated by Django 2.1.3 on 2018-11-15 21:37

import courses.programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_remove_week_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[(courses.programs.models.ProgramCategoryChoice('Finance'), 'Finance'), (courses.programs.models.ProgramCategoryChoice('Emotions'), 'Emotions'), (courses.programs.models.ProgramCategoryChoice('Physical'), 'Physical'), (courses.programs.models.ProgramCategoryChoice('Life'), 'Life')], default=None, max_length=3),
        ),
    ]
