# Generated by Django 2.1.3 on 2018-11-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='category',
        ),
    ]
